- name: Install Docker and Docker-compose
  hosts: "localhost"
  become: yes

  vars:
    docker_packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io

    debian_dependencies:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

    redhat_dependencies:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2

  tasks:
    - name: Check and print Linux version
      debug:
        var: ansible_os_family

    - block:
        - name: Update apt cache and install dependencies for Debian
          apt:
            name: "{{ item }}"
            state: latest
          with_items: "{{ debian_dependencies }}"

        - name: Install Python3 and pip for Debian
          apt:
            name:
              - python3
              - python3-pip
            state: latest

        - name: Add Docker GPG key for Debian
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present

        - name: Add Docker repository for Debian
          apt_repository:
            repo: "deb [arch=amd64] https://download.docker.com/linux/{{ item }} {{ ansible_distribution_release }} stable"
            state: present
            update_cache: yes
          with_items:
            - ubuntu
            - debian

        - name: Install Docker packages
          package:
            name: "{{ docker_packages }}"
            state: latest

        - name: Install Docker-compose
          pip:
            name: docker-compose
            state: latest
          notify: Restart Docker Debian

      when: ansible_os_family == "Debian"

    - block:
        - name: Update yum cache and install dependencies for RedHat
          yum:
            name: "{{ item }}"
            state: latest
          with_items: "{{ redhat_dependencies }}"

        - name: Install Python3 and pip for RedHat
          yum:
            name:
              - python3
              - python3-pip
            state: latest

        - name: Add Docker GPG key for RedHat
          rpm_key:
            key: https://download.docker.com/linux/{{ item }}/gpg
            state: present
          with_items:
            - centos
            - fedora

        - name: Add Docker repository for RedHat
          yum_repository:
            name: docker-ce
            baseurl: https://download.docker.com/linux/{{ item }}/$releasever/$basearch/stable
            enabled: yes
            gpgcheck: yes
            gpgkey: https://download.docker.com/linux/{{ item }}/gpg
          with_items:
            - centos
            - fedora

        - name: Install Docker packages
          package:
            name: "{{ docker_packages }}"
            state: latest

        - name: Install Docker-compose
          pip:
            name: docker-compose
            state: latest
          notify: Restart Docker RedHat

      when: ansible_os_family == "RedHat"

  handlers:
    - name: Restart Docker Debian
      service:
        name: docker
        state: restarted

    - name: Restart Docker RedHat
      service:
        name: docker
        state: restarted

